// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieaolimbpcfkojndqqap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllYW9saW1icGNma29qbmRxcWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDU0NzAsImV4cCI6MjA2MTIyMTQ3MH0.x4orCGV4ZI0314rxWZFvt7KhBppl3PTJctnlI4RtIHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);